site_name: JAX-FNO
site_description: Fourier Neural Operators written in JAX/Flax
repo_url: https://github.com/christianfenton/jax-fno
repo_name: christianfenton/jax-fno

theme:
  name: material

plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_object_full_path: false
            show_source: true
            heading_level: 1
            docstring_style: google
            merge_init_into_class: false

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Tutorials:
    - Solving the heat equation: tutorials/solving_heat_equation.md
    - Learning an antiderivative operator: tutorials/learning_antiderivative.md
  - User Guides:
    - Understanding the ODE integrator: guides/integrate_guide.md
  - API Reference:
    - Learning (jax_fno.learn): api/learn_api.md
    - Integration (jax_fno.integrate): api/integrate_api.md
